---
- name: play1.yml
  hosts: all
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
  - name: start httpd service
    service:
     name: httpd
     state: enabled
     status: started


  
